export const GET_CARDS_STARTED = 'GET_CARDS_STARTED' as const;
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS' as const;
export const GET_CARDS_FAILURE = 'GET_CARDS_FAILURE' as const;
export const ADD_ASYNC_CARD = 'ADD_ASYNC_CARD' as const;
export const CHANGE_CARD_STATUS_BASKET = 'CHANGE_CARD_STATUS_BASKET' as const;
export const CHANGE_CARD_STATUS_WISHLIST = 'CHANGE_CARD_STATUS_WISHLIST' as const;

export const ADD_CARD_BASKET = 'ADD_CARD_BASKET' as const;
export const REMOVE_CARD_FROM_BASKET = 'REMOVE_CARD_FROM_BASKET' as const;
export const INCREASE_CARD_AMOUNT = 'INCREASE_CARD_AMOUNT' as const;
export const DECREASE_CARD_AMOUNT = 'DECREASE_CARD_AMOUNT' as const;

export const ADD_CARD_WISHLIST = 'ADD_CARD_WISHLIST' as const;
export const REMOVE_CARD_FROM_WISHLIST = 'REMOVE_CARD_FROM_WISHLIST' as const;